stages:
  - run

runEarthPalette:
  image: osgeo/gdal:ubuntu-small-latest
  stage: run
  script:
    - apt install python3-pip
    - pip3 install -r requirements.txt
    - CONSUMER_KEY=$CONSUMER_KEY
    - CONSUMER_SECRET=$CONSUMER_SECRET
    - OAUTH_KEY=$OAUTH_KEY
    - OAUTH_SECRET=$OAUTH_SECRET
    - python3 earthpalette.py
  # only:
  #   -schedules